require('lazy').setup({
  'tpope/vim-sleuth',
  require 'kickstart/plugins/gitsigns',
  require 'kickstart/plugins/which-key',
  require 'kickstart/plugins/telescope',
  require 'kickstart/plugins/lspconfig',
  require 'kickstart/plugins/conform',
  require 'kickstart/plugins/cmp',
  require 'kickstart/plugins/theme',
  require 'kickstart/plugins/todo-comments',
  require 'kickstart/plugins/mini',
  require 'kickstart/plugins/treesitter',
  require 'kickstart/plugins/noice',
  require 'kickstart/plugins/snacks',
  require 'kickstart.plugins.debug',
  require 'kickstart.plugins.indent_line',
  require 'kickstart.plugins.lint',
  require 'kickstart.plugins.neo-tree',

  { import = 'custom.plugins' },
}, {
  ui = {
    icons = {
      cmd = '⟩',
      config = '',
      event = '♬',
      favorite = '★',
      ft = '✦',
      init = '',
      import = '↲',
      keys = '♪',
      lazy = '≈',
      loaded = '●',
      not_loaded = '○',
      plugin = 'λ',
      runtime = '',
      require = '',
      source = '',
      start = '▷',
      task = '√',
      list = {
        '♠',
        '♥',
        '♣',
        '♦',
      },
    },
  },
})

-- vim: ts=2 sts=2 sw=2 et
