#!/usr/bin/env dash
# Get hex rgb color under mouse cursor, put it into clipboard and create a
# notification.

sleep 2;
eval $(xdotool getmouselocation --shell)
IMAGE=`import -window root -depth 8 -crop 1x1+$X+$Y txt:-`
COLOR=`echo $IMAGE | grep -om1 '#\w\+'`
echo -n $COLOR | xclip -i -selection CLIPBOARD
notify-desktop "Color under mouse cursor: " $COLOR
