#!/usr/bin/env dash

current=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $((SINK + 1)) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
current_sink=$(pactl list short sinks | awk 'NR==1{print $1}')

volume() {
	case "$1" in 
		up)
			if [ "$current" -lt 100 ]; then
				if [ $((current + 10)) -gt 100 ]; then
					pactl set-sink-volume "$current_sink" +$((100 - current))%
				else
					pactl set-sink-volume "$current_sink" +10%
				fi
			fi
			;;
		down)
			pactl set-sink-volume "$current_sink" -10%
			;;
		toggle)
			pactl set-sink-mute "$current_sink" toggle
			;;
		*)
			echo 'Usage: volume <up/down/toggle>'
			exit 1;
			;;
	esac;
}

volume "$1"
