name: "nix-config flake check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
      with:
          fetch-depth: 0
    - uses: cachix/install-nix-action@v25
      with:
        install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.20.0pre20240119_3b20cca/install
        extra_nix_config: |
          experimental-features = ca-derivations nix-command flakes
    - run: nix flake check --show-trace
